name: Deploy to GitHub Pages  # 工作流名称

on:
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
    - name: Checkout repository  # 检出仓库代码
      uses: actions/checkout@v2

    - name: Set up Node.js using pnpm  # 设置 Node.js 和 pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest  # 安装最新版本的 pnpm

    - name: Set up Node.js version and cache dependencies  # 设置 Node.js 版本并缓存依赖
      uses: actions/setup-node@v3
      with:
        node-version: lts/*  # 使用最新的 LTS 版本的 Node.js
        cache: pnpm  # 缓存 pnpm 的依赖

    - name: Install dependencies  # 安装项目依赖
      run: pnpm install

    - name: Run lint  # 运行代码检查
      run: pnpm run check

    - name: Build project  # 构建项目
      run: pnpm run build

    - name: Deploy to GitHub Pages  # 部署到 GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GH_TOKEN }}  # 使用 GitHub token 进行认证
        publish_dir: ./dist  # 指定构建输出目录
